### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by jas777** [DusterTheFirst/Login-With-Discord#2]
![3](https://user-images.githubusercontent.com/21196093/36284906-da9f5c06-12a9-11e8-8053-3cae95abba72.png)

Code that I'm using was working before, but  now it throws Error 401 (Unauthorized), is it something with discord servers or the API itself

**Comment by DusterTheFirst** [comment]
it looks like it, could you show a gif or something of the OAuth Process

**Comment by jas777** [comment]
I was already logged in, it's code similar to this in example. I just entered site, and it froze on "LOADING", so I looked into console and I saw this

**Comment by DusterTheFirst** [comment]
ah, it might have something to do with the API storing the access token

**Comment by jas777** [comment]
Okay, hit me up when you'll know something more please

**Comment by DusterTheFirst** [comment]
try clearing the cookie cache and reload the page

**Comment by jas777** [comment]
(Forgot to close)
