### ISSUE TITLE
Possible change in OAuth2 URL format

### ISSUE THREAD

**Issue by nkmlombardi** [DusterTheFirst/Login-With-Discord#6]
I was setting this up for my community, and the login kept failing to authenticate. The URL string generated by the script separates scopes by the "+" sign, yet when I generate an OAuth2 URL from the Discord developers dashboard, it separates the scopes by %20.

I changed line 25 of `lwd.js` from:
```
scopes: parsed.scope.split("+"),
```
to: 
```
scopes: parsed.scope.split("%20"),
```

And everything works.

Thanks for your effort!

**Comment by DusterTheFirst** [comment]
Could you elaborate what exactly the problem was, cause the authentication url can use any dilimeter. Are you using your own auth url?

**Comment by DusterTheFirst** [comment]
Closed due to inactivity
