### ISSUE TITLE
Site is Bugged

### ISSUE THREAD

**Issue by BruceTheVeteran** [DusterTheFirst/Login-With-Discord#7]
The example @ https://lwd.js.org isn't working

**Comment by DusterTheFirst** [comment]
Im gonna need more information than that, what is broken, and are there any errors

**Comment by BruceTheVeteran** [comment]
I open it using google chrome and the button doesnt work, Here is an error from the script.
![image](https://user-images.githubusercontent.com/30355199/48307927-fd413c00-e52d-11e8-9de9-a8ba6e6c371c.png)

**Comment by DusterTheFirst** [comment]
Does it say what resource failed to load

**Comment by BruceTheVeteran** [comment]
Scripts.js - line 1
"LoginWithDiscord" Not Defined

**Comment by FatalErrorCode** [comment]
(To find out why it is failing, you'll probably need to clear your cache so lwd.js is not cached in your browser)
It is lwd.js that is failing to load.

![image](https://user-images.githubusercontent.com/30933518/48311938-8ea0c480-e5a7-11e8-8742-ca432b90da79.png)

**Comment by DusterTheFirst** [comment]
The problem was with the page requesting a nonexistant version of the library, this has been fixed. Thank you
