### ISSUE TITLE
Can't logout

### ISSUE THREAD

**Issue by BruceTheVeteran** [DusterTheFirst/Login-With-Discord#8]
The logout button doesn't work in the example site https://lwd.js.org/

**Comment by BruceTheVeteran** [comment]
The logout button doesn't work in the example site https://lwd.js.org/

**Comment by DusterTheFirst** [comment]
Once again, I’m going to need more information, what about the Button doesn’t work, are there any errors in the console

**Comment by mcrocks999** [comment]
Error given when using logout button within the application.
![ss](https://owo.insrt.uk/e74663c3.png)

**Comment by BruceTheVeteran** [comment]
Uncaught TypeError: this.clearAuth is not a function
    at HTMLButtonElement.logout [Line LWD.ts 127]
